// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBWkeaETiEd3Di0A6u4XfbZSDyk5ShL0',
    appId: '1:287942966857:web:00332d1e4f5fb1b22fc998',
    messagingSenderId: '287942966857',
    projectId: 'smart-roll-call-37be0',
    authDomain: 'smart-roll-call-37be0.firebaseapp.com',
    storageBucket: 'smart-roll-call-37be0.firebasestorage.app',
    measurementId: 'G-CVG7JH376Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB1XPKuOYk6N83m9YB9a_s6Frrc9nGCu4',
    appId: '1:287942966857:android:213dfed41beaf99c2fc998',
    messagingSenderId: '287942966857',
    projectId: 'smart-roll-call-37be0',
    storageBucket: 'smart-roll-call-37be0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9XEny3eypdKw5QbyU9ga55PuLGlicuCc',
    appId: '1:287942966857:ios:062349519bbbc5652fc998',
    messagingSenderId: '287942966857',
    projectId: 'smart-roll-call-37be0',
    storageBucket: 'smart-roll-call-37be0.firebasestorage.app',
    iosBundleId: 'com.example.smartRollCallFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9XEny3eypdKw5QbyU9ga55PuLGlicuCc',
    appId: '1:287942966857:ios:062349519bbbc5652fc998',
    messagingSenderId: '287942966857',
    projectId: 'smart-roll-call-37be0',
    storageBucket: 'smart-roll-call-37be0.firebasestorage.app',
    iosBundleId: 'com.example.smartRollCallFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVBWkeaETiEd3Di0A6u4XfbZSDyk5ShL0',
    appId: '1:287942966857:web:84b96a6fd6d20a472fc998',
    messagingSenderId: '287942966857',
    projectId: 'smart-roll-call-37be0',
    authDomain: 'smart-roll-call-37be0.firebaseapp.com',
    storageBucket: 'smart-roll-call-37be0.firebasestorage.app',
    measurementId: 'G-MWT13VE94C',
  );
}
